site_name: DevOps & Security Training
site_author: Basil Ndonga
site_description: A training guide for the DevOps & Security chapter.
site_url: https://docs.cloudpartner.africa

theme:
  name: material
  features:
    - search.suggest
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/css/extra.css

nav:

  - Introduction: index.md
  - GCP Setup:
      - '1. Prepare GCP Environment': 1-prepare-gcp-environment.md
      - '2. Setup Cloud SQL Database': 2-setup-cloud-sql.md
  - Backend Setup:
      - '3. Prepare GitHub & Backend Repo': 3-prepare-github-backend.md
      - '4. Setup Cloud Build for Backend': 4-setup-cloud-build-backend.md
  - Frontend Setup:
      - '5. Setup Frontend Repository': 5-setup-frontend-repo.md
      - '6. Setup Cloud Build for Frontend': 6-setup-cloud-build-frontend.md
  - Deployment:
      - '7. Access the Application': 7-accessing-the-application.md
  - Virtual Agent Class:
      - '8. Virtual Agent Class': virtual-agent-lab.md

extra: 
  generator: false  # Disable the generator tag in the HTML head