site_name: Pawa IT Cloud Mastery Training
site_author: Pawa IT Solutions
site_description: A comprehensive training guide for Cloud Mastery covering DevOps and Virtual Agents.
site_url: https://docs.cloudpartner.africa

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.instant
    - navigation.tracking
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition  # This enables !!! note syntax
  - pymdownx.details  # This enables collapsible admonitions
  
extra_css:
  - assets/css/extra.css

nav:
  - Home: index.md
  - "Introduction":
      - "Cloud Mastery Training Introduction": introduction.md
  - "GCP Migration Lab":
      - "Prepare GCP Environment": gcp-migration-lab.md
  - "Automate Securely":
      - "DevOps & CI/CD on GCP Lab": devops-lab.md
      - "Database setup": setup-cloud-sql.md
      - "Github setup": setup-github.md
      - "Setup Backend Repository": setup-backend-repository.md
      - "Setup Backend Pipeline": setup-backend-pipeline.md
      - "Setup Frontend Repository": setup-frontend-repository.md
      - "Setup Cloud Build for Frontend": setup-cloud-build-frontend.md
      - "Access the Application": accessing-the-application.md
  - "Data to Dashboards":
      - "Data Analytics & Visualization": data-analytics-lab.md
  - "Build Your Agent":
      - "Building Virtual Agent with Dialogflow CX": virtual-agent-lab.md
extra:
  generator: false

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true