site_name: DevOps & Security Training
site_author: Basil Ndonga
site_description: A training guide for the DevOps & Security chapter.

theme:
  # name: material
  # palette:
  #   # Palette toggle for light vs dark mode
  #   - scheme: default
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
  name: windmill
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.annotate
extra_css:
  - assets/css/extra.css  

# Navigation Structure
nav:
  - 'Introduction': index.md
  - '1. Prepare GCP Environment': 1-prepare-gcp-environment.md
  - '2. Setup Cloud SQL Database': 2-setup-cloud-sql.md
  - '3. Prepare GitHub & Backend Repo': 3-prepare-github-backend.md
  - '4. Setup Cloud Build for Backend': 4-setup-cloud-build-backend.md
  - '5. Setup Frontend Repository': 5-setup-frontend-repo.md
  - '6. Setup Cloud Build for Frontend': 6-setup-cloud-build-frontend.md
  - '7. Access the Application': 7-accessing-the-application.md

extra: 
  generator: false  # Disable the generator tag in the HTML head

