site_name: DevOps & Security Training
site_author: Basil Ndonga
site_description: A training guide for the DevOps & Security chapter.

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.annotate

# Navigation Structure
nav:
  - 'Introduction': index.md
  - '1. Prepare GCP Environment': 1-prepare-gcp-environment.md
  - '2. Setup Cloud SQL Database': 2-setup-cloud-sql.md
